from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class SandboxConfig(BaseModel):
    template: str = "base"
    cpu: int = 2
    mem_mb: int = 4096


class CommandResult(BaseModel):
    """Normalized result of one command run in a sandbox."""

    exit_code: int
    stdout: str = ""
    stderr: str = ""

    @property
    def ok(self) -> bool:
        return self.exit_code == 0


class SandboxEventType(str, Enum):
    FILE_CREATED = "file_created"
    FILE_MODIFIED = "file_modified"
    FILE_DELETED = "file_deleted"
    FILE_ACCESSED = "file_accessed"

    PROCESS_STARTED = "process_started"
    PROCESS_EXITED = "process_exited"

    NETWORK_CONNECTION = "network_connection"

    COMMAND_EXECUTED = "command_executed"


class SandboxEvent(BaseModel):
    """A normalized observable event coming from a sandbox.

    The monitor emits these into the engine's event bus. Sandbox events are
    raw facts (a file changed, a process started). They do *not* carry game
    meaning; rules/traps decide what they imply.
    """

    type: SandboxEventType
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # What happened (any of these depending on event type)
    path: str | None = None
    process_id: int | None = None
    process_name: str | None = None
    command: str | None = None

    # Who caused it
    user: str | None = None

    # Additional event-specific information
    metadata: dict[str, Any] = Field(default_factory=dict)


class ChallengeSpec(BaseModel):
    """Description of a challenge environment.

    Describes the *desired* environment the engine asks the SandboxManager to
    construct. The setup is deterministic — the SandboxManager translates this
    spec into concrete operations against the Solari sandbox. It should NOT be
    an arbitrary root shell script generated by an LLM.
    """

    name: str
    description: str
    win_condition: str = "prisoner_submits_flag"

    # Environment configuration
    sandbox: SandboxConfig = Field(default_factory=SandboxConfig)

    # Initial users available inside the sandbox
    prisoner_user: str = "prisoner"
    warden_user: str = "warden"

    # Secret/flag that the challenge is built around.
    flag: str

    # Files/directories that should exist when the challenge starts.
    # path -> content (text files only for now)
    files: dict[str, str] = Field(default_factory=dict)

    # Optional environment variables exported by default inside the sandbox.
    environment: dict[str, str] = Field(default_factory=dict)

    # Directories the warden watches by default (used by monitor bootstrapping).
    watched_paths: list[str] = Field(default_factory=list)
