"""empty message

Revision ID: 3b00729adfbd
Revises: a1f2c3d4e5b6
Create Date: 2026-09-20 08:48:39.975575

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b00729adfbd"
down_revision: Union[str, Sequence[str], None] = "a1f2c3d4e5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenges", sa.Column("challenge_type", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "challenges",
        sa.Column(
            "verification_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    op.drop_column("challenges", "flag")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenges", sa.Column("flag", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_column("challenges", "verification_config")
    op.drop_column("challenges", "challenge_type")
    # ### end Alembic commands ###
