"""add hints cols to challenges

Revision ID: 5e84595292f7
Revises: b9c0d1e2f3a4
Create Date: 2026-09-28 20:29:56.643304

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e84595292f7"
down_revision: Union[str, Sequence[str], None] = "b9c0d1e2f3a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("challenges", sa.Column("prisoner_hint", sa.Text(), nullable=True))
    op.add_column("challenges", sa.Column("warden_hint", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenges", "warden_hint")
    op.drop_column("challenges", "prisoner_hint")
    # ### end Alembic commands ###
