"""Initial migration

Revision ID: bbea53e69bb7
Revises: 
Create Date: 2026-09-18 20:26:29.786327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbea53e69bb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('win_condition', sa.Text(), nullable=False),
    sa.Column('sandbox_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('env_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('setup_script', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('prisoner_model', sa.String(length=255), nullable=False),
    sa.Column('prisoner_provider', sa.String(length=255), nullable=False),
    sa.Column('warden_model', sa.String(length=255), nullable=False),
    sa.Column('warden_provider', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('winner', sa.String(length=32), nullable=True),
    sa.Column('win_condition', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_challenge_id'), 'matches', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_matches_created_at'), 'matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_winner'), 'matches', ['winner'], unique=False)
    op.create_table('match_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_actor'), 'match_events', ['actor'], unique=False)
    op.create_index(op.f('ix_match_events_event_type'), 'match_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.create_index('ix_match_events_match_time', 'match_events', ['match_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_match_events_timestamp'), 'match_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_events_timestamp'), table_name='match_events')
    op.drop_index('ix_match_events_match_time', table_name='match_events')
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_event_type'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_actor'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index(op.f('ix_matches_winner'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_created_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_challenge_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('challenges')
    # ### end Alembic commands ###
